create database heroAcademy;
drop database heroAcademy;
use heroAcademy;
show tables;

select * from course;
select * from course_instructor;
select * from course_user;
select * from element;
select * from element_mapping;
select * from equipment;
select * from equipment_mapping;
select * from location;
select * from mission;
select * from race;
select * from race_mapping;
select * from skill;
select * from skill_mapping;
select * from symbol;
select * from symbol_mapping;
select * from team;
select * from user;
select * from user_address;

desc user;
desc user_address;
desc course;
desc course_instructor;
desc course_user;
desc element;
desc element_mapping;
desc equipment;
desc equipment_mapping;
desc location;
desc mission;
desc team;
desc race;
desc race_mapping;
desc skill;
desc skill_mapping;
desc symbol;
desc symbol_mapping;

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;
truncate course;
truncate course_instructor;
truncate course_user;
truncate element;
truncate element_mapping;
truncate equipment;
truncate equipment_mapping;
truncate location;
truncate mission;
truncate race;
truncate race_mapping;
truncate skill;
truncate skill_mapping;
truncate symbol;
truncate symbol_mapping;
truncate team;
truncate user;
truncate user_address;
SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;